# Generated by Django 5.1 on 2025-01-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_alter_architect_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
