# Generated by Django 5.1 on 2025-01-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_alter_architect_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="architect",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="architect",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
