# Generated by Django 5.1 on 2025-01-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_alter_architect_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
