# Generated by Django 5.1 on 2025-01-16 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0008_alter_architect_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
