# Generated by Django 5.1 on 2025-01-17 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0010_alter_architect_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="last_login",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
