# Generated by Django 5.1 on 2025-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0012_alter_architect_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
