# Generated by Django 5.1 on 2025-01-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0013_alter_architect_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="adress",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="architect",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
