# Generated by Django 5.1 on 2025-02-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0014_alter_architect_adress_alter_architect_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quoterequestproduct",
            options={"managed": False},
        ),
    ]
