# Generated by Django 5.1 on 2025-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0015_alter_quoterequestproduct_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quoterequestproduct",
            options={},
        ),
    ]
