# Generated by Django 5.1 on 2025-02-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0017_alter_quoterequestproduct_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoterequestproduct",
            name="id",
        ),
    ]
