# Generated by Django 5.1 on 2025-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0018_remove_quoterequestproduct_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequestproduct",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
