# Generated by Django 5.1 on 2025-02-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0019_quoterequestproduct_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quoterequestproduct",
            options={"managed": True},
        ),
    ]
