# Generated by Django 5.1 on 2025-02-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0020_alter_quoterequestproduct_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quoterequestproduct",
            options={},
        ),
    ]
