# Generated by Django 5.1 on 2025-02-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0021_alter_quoterequestproduct_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quoterequestproduct",
            old_name="product_id",
            new_name="product_object",
        ),
        migrations.RenameField(
            model_name="quoterequestproduct",
            old_name="quote_request_id",
            new_name="quote_request_object",
        ),
        migrations.AlterUniqueTogether(
            name="quoterequestproduct",
            unique_together={("quote_request_object", "product_object")},
        ),
    ]
