# Generated by Django 5.1 on 2025-02-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0023_alter_quoterequestproduct_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoterequestproduct",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
