# Generated by Django 5.1 on 2025-03-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0024_alter_quoterequestproduct_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardwarestorequoterequest",
            name="hardware_store_id",
            field=models.ForeignKey(
                db_column="hardware_store_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.hardwarestore",
            ),
        ),
        migrations.AlterField(
            model_name="hardwarestorequoterequest",
            name="quote_request_id",
            field=models.ForeignKey(
                db_column="quote_request_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.quoterequest",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="archi_id",
            field=models.ForeignKey(
                db_column="archi_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quoterequestproduct",
            name="product_object",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.product",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequestproduct",
            name="quote_request_object",
            field=models.ForeignKey(
                db_column="quote_request_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.quoterequest",
            ),
        ),
    ]
