# Generated by Django 5.1.12 on 2026-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0025_alter_hardwarestorequoterequest_hardware_store_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="architect",
            old_name="adress",
            new_name="address",
        ),
        migrations.AlterField(
            model_name="architect",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="architect",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
