# Generated by Django 5.1.12 on 2026-08-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0026_rename_adress_architect_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hardwarestore",
            old_name="adresse",
            new_name="address",
        ),
    ]
